services:
  - type: web
    name: agenda-mensal
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GITHUB_JSON_TOKEN
        sync: false
      - key: GITHUB_OWNER
        value: GabyQueiroz
      - key: GITHUB_REPO
        value: AgendaMensal
      - key: GITHUB_DATA_BRANCH
        value: data
      - key: GITHUB_DATA_PATH
        value: agenda-data.json
