services:
  - type: web
    name: agenda-mensal
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GIST_ID
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GIST_FILENAME
        value: agenda.json
